# Generated by Django 3.0.8 on 2020-07-20 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wishlistby',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
